set -g base-index 1
set -s escape-time 0
set -g mouse on
set -g focus-events on
set -a terminal-features 'xterm-256color:RGB'
setw -g alternate-screen on
set -s set-clipboard on

set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind f run-shell "tmux neww tmux-sessionizer"

